name: Pull Requests Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '15'
          cache: 'npm'
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run Tests
        run: |
          CI=true npm test
