name: Pull Requests Checks

on: 
  pull_request:
    branches:
    - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: |
        npm ci
    - name: Run Tests
      run: |
        CI=true npm test
